micronaut:
  application:
    name: transferSplitter
datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: none
netty:
  default:
    allocator:
      max-order: 3
